CREATE TABLE proposicao (
    ID INTEGER IDENTITY(1,1) PRIMARY KEY ,
    AUTOR VARCHAR(100),
    DATA_PRESENTACAO TIMESTAMP,
    EMENTA NVARCHAR(MAX),
    REGIME VARCHAR(50),
    SITUACCAO VARCHAR(80),
    TIPO_PROPOSICAO VARCHAR(100),
    NUMERO VARCHAR(40) UNIQUE,
    ANO INTEGER,
    CIDADE VARCHAR(60),
    ESTADO VARCHAR(80)
);


CREATE TABLE tramitacao(
    ID INTEGER IDENTITY(1,1) PRIMARY KEY,
    DATA_CRIACAO TIMESTAMP,
    DESCRICAO VARCHAR(MAX),
    LOCAL_PROPOSICAO VARCHAR(60),
    ID_PROPOSICAO VARCHAR(40),
    FOREIGN KEY (ID_PROPOSICAO) REFERENCES proposicao(NUMERO)
 
);

CREATE TABLE controle_log (
    ID INTEGER IDENTITY(1, 1) PRIMARY KEY ,
    TIPO_LOG VARCHAR(20)  UNIQUE,
    DATA_ERRO DATETIME,
    MENSAGEM_LOG VARCHAR(80)
);


BEGIN TRY
    INSERT INTO controle_log (TIPO_LOG, DATA_ERRO, MENSAGEM_LOG)
    VALUES
    ('1-1', GETDATE(), 'ERRO na verificação da conexão da API');
END TRY

BEGIN CATCH
    UPDATE 
    controle_log
    SET DATA_ERRO = GETDATE()
    WHERE TIPO_LOG = '1-1'

END CATCH



SELECT * FROM [dbo].[controle_log]
