CREATE TABLE proposicao (
    ID INTEGER IDENTITY(1,1) PRIMARY KEY ,
    AUTOR NVARCHAR(300),
    DATA_PRESENTACAO DATETIME,
    EMENTA NVARCHAR(MAX),
    REGIME VARCHAR(50),
    SITUACCAO VARCHAR(80),
    TIPO_PROPOSICAO VARCHAR(100),
    NUMERO VARCHAR(40) UNIQUE,
    ANO INTEGER,
    CIDADE VARCHAR(60),
    ESTADO VARCHAR(80),
    DATA_INSERSAO_REGISTRO DATETIME DEFAULT GETDATE(),
    DATA_ATUALIZACAO_REGISTRO DATETIME
);


CREATE TABLE tramitacao(
    ID INTEGER IDENTITY(1,1) PRIMARY KEY,
    DESCRICAO VARCHAR(MAX),
    LOCAL_PROPOSICAO VARCHAR(60),
    ID_PROPOSICAO VARCHAR(40),
    DATA_CRIACAO_TRAMITACAO DATETIME ,
    DATA_CRIACAO_REGISTRO DATETIME DEFAULT GETDATE() ,
    DATA_ATUALIZACAO_REGISTRO DATETIME ,
    FOREIGN KEY (ID_PROPOSICAO) REFERENCES proposicao(NUMERO)
 
);



-- Info de log ERRO, SUCESS, INFO
CREATE TABLE log_dag(
    ID INTEGER IDENTITY(1, 1) PRIMARY KEY ,
    TIPO_ERROR INTEGER,
    TIPO_LOG VARCHAR(20),
    URL_API VARCHAR(MAX),
    MENSAGEM_LOG VARCHAR(300) ,
    JSON_XML VARCHAR(MAX),
    JSON_ENVIO VARCHAR(MAX),
    DATA_REGISTRO DATETIME DEFAULT GETDATE()
);


CREATE TABLE dag_error (
    ID INTEGER IDENTITY(1, 1) PRIMARY KEY ,
    TIPO_ERROR INTEGER,
    NUMERO VARCHAR(40),
    URL_API VARCHAR(MAX),
    JSON_XML VARCHAR(MAX),
    JSON_ENVIO VARCHAR(MAX),
    MENSAGEM_ERRO VARCHAR(300),
    DATA_REGISTRO DATETIME DEFAULT GETDATE(),
    DATA_ATUALIZACAO DATETIME
)

-----------------------------------------------

select *
FROM log_dag;

SELECT *
FROM tramitacao
where ID_PROPOSICAO = '11063';

DELETE
FROM tramitacao
where ID_PROPOSICAO = '11063';

SELECT *
FROM proposicao
where NUMERO = '11063';

DELETE 
FROM proposicao
where NUMERO = '11063';

DELETE 
FROM dag_error;

SELECT * 
from dag_error;

INSERT INTO
dag_error  (NUMERO, URL_API, JSON_XML, JSON_ENVIO, MENSAGEM_ERRO, DATA_ATUALIZACAO)
VALUES('11064', '1', '1','1', '1', GETDATE())

DELETE
FROM dag_error
WHERE NUMERO = '11064'
