@startuml

start
:Checar Conexão API;
if (Conexão API Feita?) then (Sucesso)
    :Checar Conexão Banco;
    if (Conexão banco Feita?) then (Sucesso)
        : Recuperar dados;
        : Gravar dados Banco;
    else (Falha)
        : Envia mensagem erro log;
    endif

else (Falha)
    :Envia mensagem erro log;
    
endif
stop

@enduml
